spring.application.name=wayfare-api
spring.datasource.url=jdbc:postgresql://localhost:5432/wayfare
spring.datasource.username=wayfare
spring.datasource.password=wayfare

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true